library(xaringan)

inf_mr("Statistik_I_1_SS24.Rmd")
inf_mr("Statistik_I_2_SS24.Rmd")
inf_mr("Statistik_I_3_SS24.Rmd")
inf_mr("Statistik_I_4_SS24.Rmd")
inf_mr("Statistik_I_5_SS24.Rmd")
inf_mr("Statistik_I_6_SS24.Rmd")
inf_mr("Statistik_I_7_SS24.Rmd")
inf_mr("Statistik_I_8_SS24.Rmd")
inf_mr("Statistik_I_9_SS24.Rmd")
inf_mr("Statistik_I_10_SS24.Rmd")
inf_mr("Statistik_I_11_SS24.Rmd")
inf_mr("Statistik_I_12_SS24.Rmd")
